[package]
name = "oizo"
version = "0.1.0"
authors = ["Kevin Johnson <kevinstuartjohnson@gmail.com>"]

[dependencies]


[[bin]]
name = "oizo"
path = "src/main.rs"

[[bin]]
name = "oc"
path = "src/client.rs"

